### ISSUE TITLE
github out of date?

### ISSUE THREAD

**Issue by sherzberg** [julien-duponchelle/scrapy-elasticsearch#4]
pypi shows version 0.4, but githubs code only shows version 0.3. any thoughts why?

**Comment by julien-duponchelle** [comment]
Probably forgot to push the change, i will take a look on it after my
vacation s
Le 9 août 2014 22:51, "Spencer Herzberg" notifications@github.com a écrit
:

**Comment by julien-duponchelle** [comment]
Change pushed
